{
//=========Macro generated from canvas: cnv/cnv
//=========  (Mon Mar 16 17:01:26 2015) by ROOT version5.34/18
   TCanvas *cnv = new TCanvas("cnv", "cnv",1320,22,904,928);
   gStyle->SetOptFit(1);
   gStyle->SetOptStat(0);
   gStyle->SetOptTitle(0);
   cnv->SetHighLightColor(2);
   cnv->Range(-0.53125,-0.2013855,2.59375,1.347734);
   cnv->SetFillColor(0);
   cnv->SetBorderMode(0);
   cnv->SetBorderSize(2);
   cnv->SetTickx(1);
   cnv->SetTicky(1);
   cnv->SetLeftMargin(0.17);
   cnv->SetRightMargin(0.03);
   cnv->SetTopMargin(0.07);
   cnv->SetBottomMargin(0.13);
   cnv->SetFrameFillStyle(0);
   cnv->SetFrameBorderMode(0);
   cnv->SetFrameFillStyle(0);
   cnv->SetFrameBorderMode(0);
   
   TH1F *h_gammaD_1_cT_Z_lab_dummy = new TH1F("h_gammaD_1_cT_Z_lab_dummy","h_gammaD_1_cT_Z_lab_dummy",5,0,2.5);
   h_gammaD_1_cT_Z_lab_dummy->SetMaximum(1.239295);
   h_gammaD_1_cT_Z_lab_dummy->SetLineStyle(0);
   h_gammaD_1_cT_Z_lab_dummy->SetMarkerStyle(20);
   h_gammaD_1_cT_Z_lab_dummy->GetXaxis()->SetTitle("L_{Z} of #gamma_{D} [mm]");
   h_gammaD_1_cT_Z_lab_dummy->GetXaxis()->SetLabelFont(42);
   h_gammaD_1_cT_Z_lab_dummy->GetXaxis()->SetLabelOffset(0.007);
   h_gammaD_1_cT_Z_lab_dummy->GetXaxis()->SetTitleSize(0.06);
   h_gammaD_1_cT_Z_lab_dummy->GetXaxis()->SetTitleOffset(0.95);
   h_gammaD_1_cT_Z_lab_dummy->GetXaxis()->SetTitleFont(42);
   h_gammaD_1_cT_Z_lab_dummy->GetYaxis()->SetTitle("Normalized Fraction of events / 0.5 mm");
   h_gammaD_1_cT_Z_lab_dummy->GetYaxis()->SetLabelFont(42);
   h_gammaD_1_cT_Z_lab_dummy->GetYaxis()->SetLabelOffset(0.007);
   h_gammaD_1_cT_Z_lab_dummy->GetYaxis()->SetTitleSize(0.05);
   h_gammaD_1_cT_Z_lab_dummy->GetYaxis()->SetTitleOffset(1.3);
   h_gammaD_1_cT_Z_lab_dummy->GetYaxis()->SetTitleFont(42);
   h_gammaD_1_cT_Z_lab_dummy->GetZaxis()->SetLabelFont(42);
   h_gammaD_1_cT_Z_lab_dummy->GetZaxis()->SetLabelOffset(0.007);
   h_gammaD_1_cT_Z_lab_dummy->GetZaxis()->SetTitleSize(0.06);
   h_gammaD_1_cT_Z_lab_dummy->GetZaxis()->SetTitleFont(42);
   h_gammaD_1_cT_Z_lab_dummy->Draw("");
   
   TH1F *h_gammaD_1_cT_Z_lab = new TH1F("h_gammaD_1_cT_Z_lab","h_gammaD_1_cT_Z_lab",5,0,2.5);
   h_gammaD_1_cT_Z_lab->SetBinContent(1,0.5953518);
   h_gammaD_1_cT_Z_lab->SetBinContent(2,0.4610553);
   h_gammaD_1_cT_Z_lab->SetBinContent(3,0.3571608);
   h_gammaD_1_cT_Z_lab->SetBinContent(4,0.3212312);
   h_gammaD_1_cT_Z_lab->SetBinContent(5,0.265201);
   h_gammaD_1_cT_Z_lab->SetBinContent(6,8.050126);
   h_gammaD_1_cT_Z_lab->SetEntries(79999);

   Int_t ci;   // for color index setting
   ci = TColor::GetColor("#0000ff");
   h_gammaD_1_cT_Z_lab->SetLineColor(ci);
   h_gammaD_1_cT_Z_lab->SetLineWidth(2);
   h_gammaD_1_cT_Z_lab->SetMarkerStyle(20);
   h_gammaD_1_cT_Z_lab->GetXaxis()->SetLabelFont(42);
   h_gammaD_1_cT_Z_lab->GetXaxis()->SetLabelOffset(0.007);
   h_gammaD_1_cT_Z_lab->GetXaxis()->SetTitleSize(0.06);
   h_gammaD_1_cT_Z_lab->GetXaxis()->SetTitleOffset(0.95);
   h_gammaD_1_cT_Z_lab->GetXaxis()->SetTitleFont(42);
   h_gammaD_1_cT_Z_lab->GetYaxis()->SetLabelFont(42);
   h_gammaD_1_cT_Z_lab->GetYaxis()->SetLabelOffset(0.007);
   h_gammaD_1_cT_Z_lab->GetYaxis()->SetTitleSize(0.06);
   h_gammaD_1_cT_Z_lab->GetYaxis()->SetTitleOffset(1.3);
   h_gammaD_1_cT_Z_lab->GetYaxis()->SetTitleFont(42);
   h_gammaD_1_cT_Z_lab->GetZaxis()->SetLabelFont(42);
   h_gammaD_1_cT_Z_lab->GetZaxis()->SetLabelOffset(0.007);
   h_gammaD_1_cT_Z_lab->GetZaxis()->SetTitleSize(0.06);
   h_gammaD_1_cT_Z_lab->GetZaxis()->SetTitleFont(42);
   h_gammaD_1_cT_Z_lab->Draw("same");
   
   TH1F *h_gammaD_2_cT_Z_lab = new TH1F("h_gammaD_2_cT_Z_lab","h_gammaD_2_cT_Z_lab",5,0,2.5);
   h_gammaD_2_cT_Z_lab->SetBinContent(1,0.6884975);
   h_gammaD_2_cT_Z_lab->SetBinContent(2,0.4584472);
   h_gammaD_2_cT_Z_lab->SetBinContent(3,0.344716);
   h_gammaD_2_cT_Z_lab->SetBinContent(4,0.2803019);
   h_gammaD_2_cT_Z_lab->SetBinContent(5,0.2280374);
   h_gammaD_2_cT_Z_lab->SetBinContent(6,3.751186);
   h_gammaD_2_cT_Z_lab->SetEntries(79999);

   ci = TColor::GetColor("#ff0000");
   h_gammaD_2_cT_Z_lab->SetLineColor(ci);
   h_gammaD_2_cT_Z_lab->SetLineWidth(2);
   h_gammaD_2_cT_Z_lab->SetMarkerStyle(20);
   h_gammaD_2_cT_Z_lab->GetXaxis()->SetLabelFont(42);
   h_gammaD_2_cT_Z_lab->GetXaxis()->SetLabelOffset(0.007);
   h_gammaD_2_cT_Z_lab->GetXaxis()->SetTitleSize(0.06);
   h_gammaD_2_cT_Z_lab->GetXaxis()->SetTitleOffset(0.95);
   h_gammaD_2_cT_Z_lab->GetXaxis()->SetTitleFont(42);
   h_gammaD_2_cT_Z_lab->GetYaxis()->SetLabelFont(42);
   h_gammaD_2_cT_Z_lab->GetYaxis()->SetLabelOffset(0.007);
   h_gammaD_2_cT_Z_lab->GetYaxis()->SetTitleSize(0.06);
   h_gammaD_2_cT_Z_lab->GetYaxis()->SetTitleOffset(1.3);
   h_gammaD_2_cT_Z_lab->GetYaxis()->SetTitleFont(42);
   h_gammaD_2_cT_Z_lab->GetZaxis()->SetLabelFont(42);
   h_gammaD_2_cT_Z_lab->GetZaxis()->SetLabelOffset(0.007);
   h_gammaD_2_cT_Z_lab->GetZaxis()->SetTitleSize(0.06);
   h_gammaD_2_cT_Z_lab->GetZaxis()->SetTitleFont(42);
   h_gammaD_2_cT_Z_lab->Draw("same");
   
   TLegend *leg = new TLegend(0.46,0.6744444,0.6955556,0.7644444,NULL,"brNDC");
   leg->SetBorderSize(0);
   leg->SetTextSize(0.02777778);
   leg->SetLineColor(1);
   leg->SetLineStyle(1);
   leg->SetLineWidth(1);
   leg->SetFillColor(0);
   leg->SetFillStyle(0);
   TLegendEntry *entry=leg->AddEntry("h_gammaD_1_cT_Z_lab","1st dark photon (leading p_{T})","L");

   ci = TColor::GetColor("#0000ff");
   entry->SetLineColor(ci);
   entry->SetLineStyle(1);
   entry->SetLineWidth(2);
   entry->SetMarkerColor(1);
   entry->SetMarkerStyle(21);
   entry->SetMarkerSize(1);
   entry->SetTextFont(42);
   entry=leg->AddEntry("h_gammaD_2_cT_Z_lab","2nd dark photon","L");

   ci = TColor::GetColor("#ff0000");
   entry->SetLineColor(ci);
   entry->SetLineStyle(1);
   entry->SetLineWidth(2);
   entry->SetMarkerColor(1);
   entry->SetMarkerStyle(21);
   entry->SetMarkerSize(1);
   entry->SetTextFont(42);
   leg->Draw();
   
   leg = new TLegend(0.4566667,0.82,0.7822222,0.9066667,NULL,"brNDC");
   leg->SetBorderSize(0);
   leg->SetTextSize(0.02777778);
   leg->SetLineColor(1);
   leg->SetLineStyle(1);
   leg->SetLineWidth(1);
   leg->SetFillColor(0);
   leg->SetFillStyle(0);
   entry=leg->AddEntry("NULL","#splitline{pp #rightarrow h #rightarrow 2n_{1} #rightarrow 2n_{D} + 2 #gamma_{D} #rightarrow 2n_{D} + 4#mu}{#splitline{m_{h} = 125 GeV, m_{n_{1}} = 10 GeV, m_{n_{D}} = 1 GeV}{m_{#gamma_{D}} = 0.850 GeV, c#tau_{#gamma_{D}} = 0.5 mm}}","h");
   entry->SetLineColor(1);
   entry->SetLineStyle(1);
   entry->SetLineWidth(1);
   entry->SetMarkerColor(1);
   entry->SetMarkerStyle(21);
   entry->SetMarkerSize(1);
   entry->SetTextFont(42);
   leg->Draw();
   
   leg = new TLegend(0.17,0.935,0.97,1,NULL,"brNDC");
   leg->SetBorderSize(0);
   leg->SetTextAlign(22);
   leg->SetTextSize(0.045);
   leg->SetLineColor(1);
   leg->SetLineStyle(1);
   leg->SetLineWidth(1);
   leg->SetFillColor(0);
   leg->SetFillStyle(0);
   entry=leg->AddEntry("NULL","CMS Simulation (LHE) 8 TeV","h");
   entry->SetLineColor(1);
   entry->SetLineStyle(1);
   entry->SetLineWidth(1);
   entry->SetMarkerColor(1);
   entry->SetMarkerStyle(21);
   entry->SetMarkerSize(1);
   entry->SetTextFont(42);
   leg->Draw();
   cnv->Modified();
   cnv->cd();
   cnv->SetSelected(cnv);
}
